Algoritmo "Exerc02"
// 
//  
// Descrição   : Faça um programa que leia o nome de uma pessoa e mostre uma mensagem de boasvindas para ela:
//Ex: Qual é o seu nome? João da Silva
//Olá João da Silva, é um prazer te conhecer!
// Autor(a)    : Thaynara Vanzella
// Data atual  : 10/10/2025
Var
// Seção de Declarações das variáveis
nome: caractere
Inicio

  Escreva ("Qual é o seu nome? ")
  Leia (nome)
  EscrevaL ("Olá ", nome, ", é um prazer te conhecer!")

Fimalgoritmo