Algoritmo "semnome"
// 
//  
// Descrição   :  Desenvolva um programa que leia um número inteiro e mostre se ele é PAR ou
//ÍMPAR.
// Autor(a)    : Thaynara Vanzella
// Data atual  : 12/10/2025
Var
N: real

Inicio
      Escreva ("Digite um número :")
      Leia (N)
      Se (N%2=0) então
      Escreva ("O número", N1, " é PAR")
      senao
      Escreva ("O número", N1, " é IMPAR")
      FimSe
Fimalgoritmo