Algoritmo "Exerc02"
// 
//  
// Descrição   : Faça um programa que leia um número inteiro e mostre o seu antecessor e seu
//sucessor.
// Autor(a)    : Thaynara Vanzella
// Data atual  : 10/10/2025
Var
  N1,A,S: inteiro
Inicio

  Escreva ("Digite um número: ")
  Leia (N1)
  A <- N1-1
  S <- N1+1
  Escreval ("O antecessor de", N1, " é",A)
  Escreval ("O sucessor de", N1, " é", S)

Fimalgoritmo