Algoritmo "Exerc02"
// 
//  
// Descrição   : Crie um algoritmo que leia um número real e mostre na tela o seu dobro e a
//sua terça parte.
// Autor(a)    : Thaynara Vanzella
// Data atual  : 10/10/2025
Var
  N1,D,T: real
Inicio

  Escreva ("Digite um número: ")
  Leia (N1)
  D <- N1*2
  T <- N1/3
  Escreval ("O dobro de", N1, " é",D)
  Escreval ("A terça parte de", N1, " é ", T:5:4)

Fimalgoritmo